service: image-service

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}, 'default'}
  deploymentBucket:
      name: "pinster-serverless-deploy-${self:custom.profiles.${self:provider.stage}}"
  package:
    exclude:
      - .git/**
      - .travis.yml
      - lambda/test

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.imageUploaderBucket}/*"

    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "*"

    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource:
        - "*"

custom:
  defaultStage: dev
  profiles:
    dev: dev
    prod: prod
  customDomain:
    domainName: api-${self:provider.stage}.pinster.info
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

  # if the bucket name is changed then you must go to the resources section and change it there too!
  # This is a stupid limitation of serverless
  # https://github.com/serverless/serverless/issues/2486
  # https://github.com/serverless/serverless/issues/2749
  imageUploaderBucket: pinster-image-service


functions:
  newImageUploader:
    handler: lambda/image-uploader.upload
    events:
      - http:
          method: post
          path: images/upload
          cors: true
    memorySize: 1024
    environment:
          BUCKET_NAME: ${self:custom.imageUploaderBucket}

  startExecution:
    handler: lambda/step-functions.startExecution
    events:
      - s3:
          bucket: ${self:custom.imageUploaderBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
    memorySize: 128
    environment:
      STATEMACHINE_ARN: ${self:resources.Outputs.ThumbnailProcessor.Value}

  generateThumbnail:
    handler: lambda/image-manipulator.generateThumbnail
    memorySize: 1024

  moderate:
    handler: lambda/moderator.moderate
    memorySize: 128

  notify:
    handler: lambda/integrator.notify
    memorySize: 128

stepFunctions:
  stateMachines:
    thumbnailProcessor:
      name: thumbnailProcessor
      definition:
        Comment: "StateMachine that turns raw images into thumbnails"
        StartAt: Moderate
        States:
          Moderate:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-moderate"
            Next: GenerateThumbnail
            Catch:
            - ErrorEquals:
              - ModerationThresholdExceeded
              Next: NotifyIntegrations
          GenerateThumbnail:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-generateThumbnail"
            Next: NotifyIntegrations
          NotifyIntegrations:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-notify"
            End: true

resources:
  Resources:
  # if the bucket name is changed then this resource name must be changed! This is a stupid limitation of serverless
  # https://github.com/serverless/serverless/issues/2486
  # https://github.com/serverless/serverless/issues/2749
    S3BucketPinsterimageservice:
      Type: 'AWS::S3::Bucket'
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, HEAD]
              AllowedOrigins: ['*']
              MaxAge: '3600'

  Outputs:
    ThumbnailProcessor:
      Description: The ARN of the ThumbnailProcessor state machine
      Value:
        Ref: ThumbnailProcessor

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-domain-manager
